version: "2.1"
services:
  code-server:
    image: codercom/code-server:latest
    #build: .
    container_name: code-server
    #command: export PATH=$HOME/project/ghc/.cabal/bin:$PATH
    user: 1000:1000
    privileged: true
    volumes:
      - ./home:/home/coder:rw
      - ./config.yaml:/home/coder/.config/code-server/config.yaml:rw
    devices: 
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6000:8080
